name: personal-workout-tracker

services:
  db:
    image: postgres:17
    env_file: .local.env
    ports:
      - 5432:5432
  backend:
    image: server
    build: ./server
    env_file: .local.env
    ports:
      - 8000:8000
  frontend:
    image: web
    build: ./web
    env_file: ./web/.env.local
    ports:
      - 3000:3000